Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [11]:
"""
1. check whether the number of columns is passed. If not specified then a square array is returned (n = len(vct)).
2. check the order of the power. If True, the powers increase from left to right, if False (the default) they are reversed.

"""
import numpy as np

def my_func_vandermonde(vct,n=None,bln=False):
    
    if n==None: 
        
        n=len(vct)
        if bln==False:
            return np.column_stack([vct**(n-1-i) for i in range(n)])
        else:
            return np.column_stack([vct**i for i in range(n)])
    else:
        
        if bln==False:
            return np.column_stack([vct**(n-1-i) for i in range(n)])
        else:
            return np.column_stack([vct**i for i in range(n)])

In [12]:
my_func_vandermonde(np.array([4, 1, 2, 5]))

array([[ 64,  16,   4,   1],
       [  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [125,  25,   5,   1]], dtype=int32)

In [13]:
my_func_vandermonde(np.array([4, 1, 2, 5]),4)

array([[ 64,  16,   4,   1],
       [  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [125,  25,   5,   1]], dtype=int32)

In [14]:
my_func_vandermonde(np.array([4, 1, 2, 5]),4,False)

array([[ 64,  16,   4,   1],
       [  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [125,  25,   5,   1]], dtype=int32)

In [15]:
my_func_vandermonde(np.array([4, 1, 2, 5]),4,True)

array([[  1,   4,  16,  64],
       [  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   5,  25, 125]], dtype=int32)